# Porta do proxy
http_port 3128
visible_hostname ProxyEric_Guilherme


# Bloquear site de apostas
acl site_bloqueado url_regex -i "/etc/squid/bloqueado.txt"


# Regras de acesso
http_access deny site_bloqueado
deny_info http://200.10.0.17/ site_bloqueado

